### ISSUE TITLE
Temperature is not displayed on icon

### ISSUE THREAD

**Issue by gtsiam** [Veske/gnome-shell-extension-freon#4]
I might be wrong, but I assume that when clicking on the status bar icon and selecting something (e.g. average), the temperature should be displayed on the icon.

Instead, 3 dots are shown
![image](https://user-images.githubusercontent.com/7459196/31071645-79e3f2a2-a76d-11e7-8718-4ae4f2ca83fe.png)

I am running on fedora 26, Gnome 3.24.2

**Comment by pedrxd** [comment]
Working fine on my pc. Probably your status bar doesn't have space for display it.

**Comment by gtsiam** [comment]
Actually, it fixed itself after a restart. I should have mentioned that earlier, but still, it shouldn't do that even at first.
